// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjoGxSRXvbossumC4sVr-rmczQO4Ibpk',
    appId: '1:893876454211:web:0769827e0bf4ce71af25f6',
    messagingSenderId: '893876454211',
    projectId: 'budget-buddy-eec37',
    authDomain: 'budget-buddy-eec37.firebaseapp.com',
    storageBucket: 'budget-buddy-eec37.firebasestorage.app',
    measurementId: 'G-8FZCESYQ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9FiYhSyWpQ1FBklcv_uHA00i09dSOG54',
    appId: '1:893876454211:android:8b5d53a885a857c5af25f6',
    messagingSenderId: '893876454211',
    projectId: 'budget-buddy-eec37',
    storageBucket: 'budget-buddy-eec37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplbHroq80sS0g1aU3a_xWakIGRcKvAtg',
    appId: '1:893876454211:ios:30349ff83382c1d4af25f6',
    messagingSenderId: '893876454211',
    projectId: 'budget-buddy-eec37',
    storageBucket: 'budget-buddy-eec37.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBplbHroq80sS0g1aU3a_xWakIGRcKvAtg',
    appId: '1:893876454211:ios:30349ff83382c1d4af25f6',
    messagingSenderId: '893876454211',
    projectId: 'budget-buddy-eec37',
    storageBucket: 'budget-buddy-eec37.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtjoGxSRXvbossumC4sVr-rmczQO4Ibpk',
    appId: '1:893876454211:web:563e19ac041b1122af25f6',
    messagingSenderId: '893876454211',
    projectId: 'budget-buddy-eec37',
    authDomain: 'budget-buddy-eec37.firebaseapp.com',
    storageBucket: 'budget-buddy-eec37.firebasestorage.app',
    measurementId: 'G-TT9YKWM124',
  );
}
